### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by devfoo-one** [devfoo-one/WTH_WS16-Experiment#1]
Unserem fancy Versuchsplan nach brauchen wir Audio für 100 - 18100Hz. Marcel meinte dass wir uns auf den Frequenzbereich 100-4100Hz konzentrieren sollten. (Laut ihrem Feedback).

Daraus ergeben sich zwei Fragen:

1. Welchen Frequenzbereich wollen wir abdecken?
2. Wie wollen wir das technisch realisieren?

Zu 2. hätte ich ne Idee. Wir brauchen pro Frequenz X 3 Soundfiles:

- File1: X auf beiden Seiten gleichlaut
- File2: X wird links mit 1 dB / sec lauter
- File3: X wird rechts mit 1 dB / sec lauter

Dann können wir zunächst *File1* zufällig lang abspielen... anschließend wird per Zufall *File2* oder *File3* abgespielt... Ab dem Beginn können wir die Zeit bis zu nem Tastendruck messen und aus der Dauer den dB Unterschied ableiten.

**Comment by devfoo-one** [comment]
Stelle fest: Ich schrieb Käse. Wir wollen ja gar nix mehr mit Stereo machen. Jetzt verstehe ich auch unser Problem hier... wir schrieben "...die Amplitude stufenlos in einem Bereich von 10dB(SPL) bis 80dB(SPL) erhöht..." ... hmm... nur das sind absolute Werte die wir ohne genormtes Ausgabegerät gar nicht hinbekommen... da wir das Problem eh haben werden können wir nur folgendes machen:

1. Uns für einen Startwert zwischen 0-1 für den Ton entscheiden
2. Den Ton mittels `MakeSineWave()` dann mit ner Schleife irgendwie erhöhen

Das Verhältnis zwischen Initialwert und gemessenem Wert kann dann in dB ausgedrückt werden (bspw. entsprechen 6dB einer Verdoppelung)

Damit rennen wir zwar gänzlich am Versuchsplan vorbei, aber naja... so is das Leben halt.

**Comment by devfoo-one** [comment]
Oke, aktueller Forschungsstand:

Wir kriegen die stufenlose Lautstärkeerhöhung mit `MakeSineWave` nicht hin, da ein selbst eine leichte Änderung der Lautstärke ziemlich fies den Ton abhakt. Allerdings könnte es ausreichen... hier mal ein Beispiel:

```R
define Start(lParameter) {
    gWindow <- MakeWindow("grey")
    frequencies <- Sequence(400,4400, 400)
    loop(freq, frequencies) {
        sound <- MakeSineWave(freq, 1000, 0.1)
        PlayBackground(sound)
        Print(freq)
        response <- WaitForListKeyPressWithTimeout(["a"], 1000, 1)
        Stop(sound)
        Wait(100)
        intensities <- Sequence(0.1, 0.5, 0.001)
        loop(intensity, intensities) {
            Print(freq + " - " + intensity)
            sound <- MakeSineWave(freq, 100, intensity)
            PlayBackground(sound)
            response <- WaitForListKeyPressWithTimeout(["a"], 90, 1) #little less delay than sound buffer
        }
    }
}
```

EDIT: Aus unserem bisherigen Code kriege ich nur den ersten Ton raus, und weiß auch noch nicht warum.

**Comment by devfoo-one** [comment]
Wenn wir uns auf zehn Frequenzen einigen würden, dann könnte ich auch Soundfiles dazu machen. Dann müssen wir nur die Dauer messen. Frequenzen würd ich 400, 800, 1200, ... , 4400 vorschlagen.

**Comment by oishiikushi** [comment]
Ich hatte beim Frequenzbereich einfach die Hörbreite des Menschen angegeben, aber das klappt wohl nicht mit Sinustönen. Wir sollen uns auf 100-4100 beschränken, ist richtig. Hört man sonst nicht oder das Ohr geht kaputt.. Stereo testen wollten wir nicht machen, nur Lautstärke erhöhen.

**Comment by pille125** [comment]
Ich denke, das 10 Frequenzen im Bereich 100-4100 passen müsten. Vorschlag:
100, 500, 900, 1300, 1700, 2100, 2500, 2900, 3300, 3700
ggf. könnte man noch 4100 als 11. Frequenz nehmen. 

Was ich mich noch Frage, ist wie wir auf die Reaktion des Probanden reagieren. Also was passiert, wenn der Proband eine Taste drückt, er also eine Änderung wahrgenommen hat? Soll das Programm einfach alle Keystrokes aufnehmen incl. Timestamp, oder soll das Programm gleich abbrechen?

**Comment by oishiikushi** [comment]
Ich würde sagen, Ton stoppen und zum nächsten Test springen. Dann weiß der Proband, das sein Tastendruck angekommen ist. Läuft der Ton einfach weiter, müssen wir nachfolgende Tastenhits (in dem jeweiligen Test) sowieso ignorieren und der Proband könnte verwirrt sein, ob seine Reaktion erkannt wurde.

**Comment by pille125** [comment]
gutes Argument :) Seh ich das Richtig, dass wir dann quasi 10 Unterschiedliche Tests haben? (also einen für jede Frequenz?). Irgendwie steh ich grad ein bisschen auf dem Schlauch ;)

**Comment by oishiikushi** [comment]
Ja, 10 Tests. In jedem haben wir eine Frequenz, die dann jeweils lauter wird.

**Comment by pille125** [comment]
alles klar dann hab ich das doch richtig verstanden ;) seid ihr Heute in SE?

**Comment by oishiikushi** [comment]
Hab mal mit deinem loop rumgespielt, @devfoo-one Ich denke, die MakeSineWave() können wir vergessen. Ich vermute stark, daß die jeweils eine neue Audiodatei generiert. Dadurch wird die Erhöhung der Lautstärke niemals smooth vonstatten gehen. Bei mir hab ich jedesmal, wenn eine neue Datei gestartet wird, einen kurzen Knacksound. Bei dem inneren Loop ergibt das also: knack, Ton, knack (etwas lauter) Ton, knack, (etwas lauter) Ton, usw. Hat jemand Ahnung/Besitz von Audioprogrammen, in dem man eine Audiospur programmieren kann (so Aftereffects-mäßig, nur für Audio?)

**Comment by pille125** [comment]
also in Multimedia Processing hatten wir ein Mathlab file für die Generierung von sinus wav files, das müsste man halt erweitern auf die Amplituden änderung. Leider ist meine Testversion abgelaufen, mal schauen ob ich irgendwo ne Vollversion finde. :)

**Comment by pille125** [comment]
http://www.audiocheck.net/audiofrequencysignalgenerator_sinetone.php
Das könnte eigentlich schon das sein was wir brauchen :) ich werds mal ausprobieren ;)

**Comment by pille125** [comment]
Okay also das generieren müsste mit o.g. site Funktionieren, jedoch müssten wir für jede Amplitude ein kurzes wav File erstellen und diese dann zusammenschneiden. In welchem Schritten wollen wir denn die Amplitude hochsetzen?

**Comment by pille125** [comment]
Mein Vorschlag für die Amplituden wäre:
-72, -62, -52, -42, -32, -22, -12, -2 dBFS
-72 ist quasi kaum hörbar und -2 sollte für jeden Probanden Hörbar sein. Wird halt eine Klickorgie bei 80 Files =P 
ggf. könnte es auch sinn machen statt in 10er schritten mit kleineren Schritten vorzugehen, da ich denke das kein Proband mehr als -50 dB braucht

**Comment by oishiikushi** [comment]
Klingt gut.

**Comment by pille125** [comment]
hab euch mal ne Mail geschickt mit nem kleinen testfile. sind 5 Amplituden (72, 67, 62, 57, 52 dBFS), bei der Frequenz 1100 hz. Pro Amplitude hab ich ne Dauer von 3 s eingestellt. Klingt schonmal ganz gut :)

**Comment by oishiikushi** [comment]
Sauber. D.h. da wir die Möglichkeit haben, Sound-Files zu precompilen, sollten wir erstmal 10 Files generieren, jeweils eine Frequenz mit Lautstärkeänderung. Im PEBL-Code dann einfach als Array laden und nach Testindex abspielen (test1 -> wav1 usw).

**Comment by pille125** [comment]
soweit der plan :) Ich würde bis/in SE die Files vorbereiten :)

**Comment by oishiikushi** [comment]
Nice. Die Amplitudenänderung sollte in jedem File gleich/bekannt sein, damit wir im Code die Zeiten korrekt messen und für die Auswertung speichern können.

**Comment by pille125** [comment]
jo :)

**Comment by pille125** [comment]
so sound files sind fertig :)
[SineFiles.zip](https://github.com/devfoo-one/WTH_WS16-Experiment/files/687297/SineFiles.zip)

**Comment by pille125** [comment]
Pro file gilt: dauer jeder Amplitude 3 Sekunden, Amplitudenskala: (-67, -62, -57, -52, -47, -42, -37, -32, -27, -22, -17, -12, -7, -2 dBFS)

**Comment by devfoo-one** [comment]
Ich fänds besser wenn die Änderung stufenlos wäre. Bzw. müssten die Schritte kleiner gewählt werden. Ich hab damals in MTA gelernt das 3dB der minimal wahrnehmbare Lautstärkeunterschied ist. 6dB ist doppelte Lautstärke. Wir müssen den Bereich 0 - +6dB untersuchen. Ich mach dazu gleich mal n Sample.

**Comment by devfoo-one** [comment]
[sounds_0-6db.zip](https://github.com/devfoo-one/WTH_WS16-Experiment/files/687367/sounds_0-6db.zip)

Hier sind jetzt die Frequenzen, welche über 30sec linear lauter werden (bis +6dB) Ich würde diese verwenden.

**Comment by pille125** [comment]
mega cool :) wie hast du den gleichmäßigen übergang hingekriegt? :)

**Comment by devfoo-one** [comment]
In Audacity nen Sinuston erzeugt und dann nen Fadeup auf +6dB

**Comment by pille125** [comment]
nice 👍

**Comment by devfoo-one** [comment]
habs mal gepushed.
