### ISSUE TITLE
welcomeLabel wird bei mir nicht angezeigt

### ISSUE THREAD

**Issue by devfoo-one** [devfoo-one/WTH_WS16-Experiment#2]
```
welcomeLabel <- EasyLabel("Press any key to start the tests", gVideoWidth / 2, gVideoHeight / 2, gWindow, 44)
    Draw()
    WaitForAnyKeyDown()
```

Ich verstehe nicht warum? Die anderen `EasyLabel` funktionieren. Ist das bei euch auch so?

**Comment by oishiikushi** [comment]
Nö, ich sehe den Smiley und welcome-Text. Probier mal nen initialen Draw()-Call gleich nach MakeWindow(), was anders fällt mir auf die Schnelle nicht ein.

**Comment by devfoo-one** [comment]
Nope, leider nicht. Auch bei `Draw()` direkt hinterm `MakeWindow`seh kein Smiley und keinen welcome Text. Erst wenn ich ne Taste drücke sehe ich "Press A if you hear a sound".

@oishiikushi downgradest du dein pebl auf 0.14 und checkst das nochmal?
@pille125 geht das bei dir?

Ich hab jetzt leider nicht unbedingt Lust ne Windows7 VM aufzusetzen und darin zu testen. Eventuell hat ja jemand eine schon fertig.

**Comment by pille125** [comment]
also bei mir wird der Smiley mit der Welcome Message angezeigt. Hast du die Mac version oder die Windoof version?

**Comment by devfoo-one** [comment]
OS X 0.14... gut dann bin ich ja beruhigt. Muss ja nur auf Windows funktionieren.

**Comment by pille125** [comment]
wir schauen das das morgen auf den Laborrechnern läuft :) ich geh eh davon aus das sie ne woche aufschub gewährt wenn was nicht läuft

**Comment by oishiikushi** [comment]
Wir sollten nochmal probieren, ein leeres Label am Anfang zu drawn. Wenn nur das erste nicht geht wie du sagst @devfoo-one , das wär das vielleicht ein workaround.

**Comment by oishiikushi** [comment]
und ich hab kein Bock zu downgraden :P
